### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by jithinktom** [yury-dymov/redux-oauth-client-demo#1]
Sorry if I'm being naive

**Comment by yury-dymov** [comment]
Hi @jithinktom,

Somehow scripts in `package.json` didn't work as expected.
I updated the package and added [Installation section](https://github.com/yury-dymov/redux-oauth-client-demo#installation) to [README](https://github.com/yury-dymov/redux-oauth-client-demo)

Let me know, if I can further help
